[env.development]
TARGET_PATH = "target/x86_64-pc-windows-msvc/debug"

[env.production]
TARGET_PATH = "target/x86_64-pc-windows-msvc/release"
BUILD_FLAGS = "--release"

[tasks.build-driver]
script = [
    "cargo build %BUILD_FLAGS%"
]

[tasks.rename]
dependencies = ["build-driver"]
ignore_errors = true
script = [
    "cd %TARGET_PATH%",
    "del mdrv.sys",
    "rename mdrv.dll mdrv.sys",
]

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = [
    "call \"%ProgramFiles(x86)%\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat\"",
    "if not exist AlfredoSauce.cer ( makecert -r -pe -ss PrivateCertStore -n CN=AlfredoSauce AlfredoSauce.cer ) else ( echo Certificate already exists. )",
    "signtool sign /a /v /s PrivateCertStore /n AlfredoSauce /t http://timestamp.digicert.com /fd SHA256 %TARGET_PATH%/mdrv.sys"
]
